### ISSUE TITLE
Use with Brave browser & possible workaround

### ISSUE THREAD

**Issue by joeweaver** [samhh/bukubrow-host#17]
I decided to see if I could get this and the associated web extension running from Brave.

Since Brave is chromium based, I tried running `bukubrow --install-chromium `.  This does not fully work.  

Copying `~/.config/chromium/NativeMessagingHosts/com.samh.bukubrow.json`
to the `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/` directory
appears to fix the issue.

**Comment by joeweaver** [comment]
See PR #18

**Comment by joeweaver** [comment]
This fell off my radar, sorry.

**Comment by samhh** [comment]
No worries. GitHub on the other hand...

> SamHH linked a pull request that will close this issue on 8 Feb

:eyes:
