### ISSUE TITLE
BSD Support

### ISSUE THREAD

**Issue by anoduck** [samhh/bukubrow-host#20]
Just wondering if it is possible to build with OpenBSD. I could try to build using the darwin flag...

**Comment by samhh** [comment]
Truth be hold I know nothing at all about BSD as a development platform - let me know how you get on!

**Comment by anoduck** [comment]
Wow, I cannot believe how easy that was. Rust is a great language, and I am becoming a big fan of it. 

I simply executed `cargo build --release` and it compiled successfully without a hitch. Now I just need a copy of the host file to stick in the firefox folder.

@SamHH For sake of saving time, could I get you to paste a copy of the json host file to a gist. That way I know what it should look like. 
Also, I have added openbsd as a target to path.rs but for some reason cargo still does not recognize it. I am updating my version of cargo to see if this resolves the issue. But we might have to just use the same json host file for OpenBSD that we use for Linux, the paths should be nearly identical.

**Comment by samhh** [comment]
Yeah, Rust is really nice. For my own interests I've been considering a rewrite in Haskell but I'm beginning to lean against it given how much friendlier Rust is to outside contributors.

Here's my host JSON on Linux for Firefox:

```
{"name":"com.samhh.bukubrow","description":"Bukubrow host for the Firefox extension","path":"/usr/bin/bukubrow","type":"stdio","allowed_extensions":["bukubrow@samhh.com"]}
```

For me that's at `~/.mozilla/native-messaging-hosts/com.samhh.bukubrow.json` per `/src/hosts/paths.rs`.

**Comment by samhh** [comment]
Had someone email me that they successfully compiled and ran this project on FreeBSD by simply applying the following patch:

```
--- src/hosts/paths.rs.orig    2020-05-05 16:57:29 UTC
+++ src/hosts/paths.rs
@@ -16,7 +16,7 @@ enum OsType {
  }

  fn get_os_type() -> OsType {
-    if cfg!(target_os = "linux") {
+    if cfg!(target_os = "linux") || cfg!(target_os = "freebsd") {
          OsType::Linux
      } else if cfg!(target_os = "macos") {
          OsType::MacOS
```

**Comment by samhh** [comment]
I'd be curious if anyone on BSD could verify if master now works for them (as of https://github.com/samhh/bukubrow-host/commit/53617af8cd96d000e4e237e3f2582371c8ea0f4a).

**Comment by anoduck** [comment]
Since I disappeared off to narnia for a bit. I might try this again.

**Comment by anoduck** [comment]
Sadly, no...it still hates me. 
Performing system wide update, will try again once complete. 
Was unable to compile using make command, and with target set to anything `--target=x86_64-*`. Resulted in rustc error `E0463`. 
Ran `cargo build` without any flags and compiled successfully, but was then unable to install firefox and recieved the error `unrecognized operating system`. 
Will provide more information after update.

**Comment by anoduck** [comment]
From what I can tell, your code works well as it should, and the issue is OpenBSD specific not only to your plugin, but other plugins that require firefox to be able to execute an external command. 
[Reference tridactyl's native messenger issue #43](https://github.com/tridactyl/native_messenger/issues/43)

I am going to bring this to the attention of the firefox maintainer for OpenBSD and see what unfurls.
