### ISSUE TITLE
Latest bukubrow fails to locate Buku database, release 5.1.0 does however work

### ISSUE THREAD

**Issue by sandersantema** [samhh/bukubrow-host#29]
It seems that the fix for finding the database on macOS [commit](https://github.com/samhh/bukubrow-host/commit/485b5afff952b72940b43ca130b1d018588f115c) actually caused a regression on linux. The latest git version doesn't work, version 5.1.0 does however work correctly on linux. 

Some relevant info:
```bash
$ echo $XDG_DATA_HOME
/home/username/.local/share
```
Location of `bookmarks.db`:
`/home/sandersantema/.local/share/buku/bookmarks.db`

**Comment by samhh** [comment]
Works for me on Linux, but the difference seems to be that my `$XDG_DATA_HOME` isn't set. Fun fun fun...

**Comment by samhh** [comment]
[Oops.](https://github.com/samhh/bukubrow-host/commit/099ee938486a3dd9c36527b823bab4d2b7900dd3)

Let me know if this fixes master for you. :slightly_smiling_face:

**Comment by sandersantema** [comment]
It's working now! It does seem somewhat slower when deleting bookmark and clicking on the `more` button but I might just be imagining this.
