### ISSUE TITLE
Distribute via package managers (AUR, Homebrew, etc)

### ISSUE THREAD

**Issue by samhh** [samhh/bukubrow-host#3]
- [x] [AUR](https://aur.archlinux.org/packages/bukubrow/)
- [ ] Homebrew
- [ ] Others?

**Comment by m040601** [comment]
> What is browserpass doing?

Just my 2 cents, trying to make the bukubrow host/extension as simple, clean and straightforward for end users as possible. Sorry I cant contribute with code as I dont know node/rust.

Another extension worth studying to see how they do things is
https://github.com/persepolisdm/Persepolis-WebExtension

Persepolis itself, https://github.com/persepolisdm/persepolis,
is just a great gui to the aria2c download manager.
So this all makes a great open source "download manager/interceptor" solution for firefox.

So just like browserpass and  buku we have 3 pieces of the puzzle:
- the application itself (pass, buku or aria2)
- the "host" or "native" glue (browserpass-native, bukubrow-host)
- the browser extension (browserpass-extension, bukubrow-extension)

The subtle thing needed is for this "registering" the extension. I  personally am against trying to to this on a system level. Trying to mess with the users system writing to /usr/lib/mozilla/native-messaging-hosts with complicated install.sh scripts.

Let's try concentrating on the users home dir.
$HOME/.mozilla/native-messaging-hosts/
a file called, com.XYZ.ABC.json, has to be created containing a pointer to the binary

Right now, bukubrow (host) needs this additional step to do that:
bukubrow --install-firefox

With https://github.com/persepolisdm/Persepolis-WebExtension this step is not needed.
Just by installing the extension from Mozilla addons it does this for you.
That is a file called, com.persepolis.XYZ.json is created in $HOME/.mozilla/native-messaging-hosts/ pointing to the standard persepolis binary location


https://github.com/SamHH/bukubrow-host/issues/3

**Comment by samhh** [comment]
Unfortunately the Persepolis webext isn't creating the host file, the application is. It's doing so in anticipation of you potentially using the webext regardless of whether you actually do or not. Hence, when you install the webext, it immediately works. I've tested this just now by installing only the Persepolis application; the hosts for all browsers were immediately created and symlinked without the webext. The relevant code is here: https://github.com/persepolisdm/persepolis/blob/master/persepolis/scripts/browser_integration.py

Bukubrow's native has no such luxury. It has no direct integration into Buku as a distinct project, and there's generally no reason you'd run Bukubrow's native except because you need it for the webext.

**Comment by m040601** [comment]
> Persepolis webext isn't creating the host file, the application is. 

Ahh , I see. I missed that. Apologies for my ignorance as a non developer if I rushed to fast making suggestions to bukubrow. My only goal is go make bukubrow (the important missing piece) as straightforward as simple to install and use for buku end users.

So the end user will always need the extra  step after downloading,
bukubrow --install-firefox.

Could you update the README and **make this more prominent** ?
I know you already have there:

> Install the host file for your browser via the executable; options can be viewed with bukubrow --help.

But this only helps making the whole setup less cryptical.

Anyway thanks for your effort in this project.
Great thing that you release a compiled binary on github releases (from azure ?).
This is absolutely essential !!!
It will make creating and AUR binary package "bukubrow-host-bin" easy, and avoid downloading the entire cargo/rust toolchain for end users.
Another AUR source based package "bukubrow-host-git" and "bukubrow-host" could be produced for the ones who want to compile themselves.

Once this gets a good polish,  enough traction and a good user base, it may even end up moving from the AUR to  an official Arch packgage . Just like it happend with browserpass host/extension with the great work of Maxim Baz, https://www.archlinux.org/packages/?sort=&q=browserpass&maintainer=&flagged=

**Comment by samhh** [comment]
Thanks for the kind words :smile: Suggestions are always welcome!

Yep, Azure was the only platform I could find that was free for open source projects and allowed cross-compiling across at least Linux and macOS.

The README is a bit rushed given the repo split. I've just updated it, hopefully it's a bit clearer now.

As for the AUR, I'm probably going to go with `bukubrow-host` to start with just as it's probably easier if building is left to the consumer. I'm not sure yet how reliable the Azure builds are...

**Comment by samhh** [comment]
Bukubrow is now on the [AUR](https://aur.archlinux.org/packages/bukubrow/)! :confetti_ball:

**Comment by piegamesde** [comment]
Bukubrow is also [in nixpkgs](https://search.nixos.org/packages?channel=unstable&query=buku)

**Comment by samhh** [comment]
Thanks for letting me know, I've updated the README.
