### ISSUE TITLE
Suggestion: Don't close bukubrow when adding a bookmark automatically

### ISSUE THREAD

**Issue by sandersantema** [samhh/bukubrow-host#33]
On my machine using the KDE desktop bukubrow automatically closes when for instance an on screen display (volume etc.) pops up. When you're adding a bookmark you lose it, so I think it might be better to not automatically close bukubrow when adding bookmarks if possible.

**Comment by samhh** [comment]
Unfortunately this is to the best of my knowledge a limitation of WebExtensions on all platforms and out of our control.

**Comment by sandersantema** [comment]
That's a shame, but might it be possible to then keep the state of bukubrow itself the same when it closes? i.e. having "add bookmark" window only disappear when the user clicks on "add bookmark", the back arrow or potentially pressing the `esc` key, regardless of bukubrow itself being visible?

**Comment by samhh** [comment]
Ah, that's a nice idea for a workaround. Mind opening an issue in the webext repo? :slightly_smiling_face:

**Comment by sandersantema** [comment]
> Ah, that's a nice idea for a workaround. Mind opening an issue in the webext repo? slightly_smiling_face

For sure, that's the proper place and I've got the two mixed up :)
