### ISSUE TITLE
Specify custom install location

### ISSUE THREAD

**Issue by piegamesde** [samhh/bukubrow-host#36]
I have two chromiums with different user-data-dir locations. The same feature also exists for other browsers too. It would be nice if one could optionally specify a custom data dir location to use for the installation process.

**Comment by samhh** [comment]
To clarify, that's custom locations for what for example by default for Chromium would go into `~/.config/chromium/NativeMessagingHosts/`?

Is this feature native to the browsers or is it added by packagers?

**Comment by piegamesde** [comment]
Exactly. If I set `~/.config/chromium2` as my data location, then the extension should be installed to `~/.config/chromium2/NativeMessagingHosts/`.

This is a browser feature, see <https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md>. In Firefox, the data directory seems to be bound to the use profile (whereas in chrome they are separate and every data directory has its own set of profiles), but I'm not sure.

**Comment by samhh** [comment]
Gotcha.

I'm thinking the most flexible way to handle this would be to add a new flag, something like `--install-path`, which allows you to specify the install location alongside `--install-chromium` et al (which are still helpful as some browsers have different manifest formats).

How does that sound?

**Comment by samhh** [comment]
If you're able to it'd be great to get some feedback on the [custom-install-dir](https://github.com/samhh/bukubrow-host/tree/custom-install-dir) branch. :slightly_smiling_face: 

There's a breaking change here that you can no longer provide multiple conflicting flags/options e.g. both `-o` and `-l`; program structure is simplified and it removes a logical ambiguity around how the new `--install-dir` flag behaves when there are multiple browser installation flags provided. The help message is a bit (more) confusing, I don't love the library we're using for handling CLI arguments - but hopefully this suffices nonetheless.

**Comment by samhh** [comment]
https://github.com/samhh/bukubrow-host/commit/b61f873006c2ca5edd25671e183bdb188b5e7fe2
