### ISSUE TITLE
Was Edge installation removed?

### ISSUE THREAD

**Issue by farzadmf** [samhh/bukubrow-host#37]
Hi @samhh 

I recently noticed that, for some reason, my Edge (Dev Channel) on Linux has stopped working and is giving me an error:
![image](https://user-images.githubusercontent.com/5768792/124164990-5360a600-da6f-11eb-97fa-ac8736c6cee0.png)

I decided to re-install it, but when I do `bukubrow --help`, I don't see the Edge option anymore :thinking: 
```
bukubrow 5.2.0
Sam A. Horvath-Hunt
Bukubrow native messaging host installer

USAGE:
    bukubrow [FLAGS] [OPTIONS]

FLAGS:
    -h, --help                Prints help information
        --install-brave       Install the native messaging host for Brave
        --install-chrome      Install the native messaging host for Chrome
        --install-chromium    Install the native messaging host for Chromium
        --install-firefox     Install the native messaging host for Firefox
        --install-vivaldi     Install the native messaging host for Vivaldi
    -l, --list                Print all bookmarks in a list to stdout
    -V, --version             Prints version information

OPTIONS:
    -o, --open <ID[,ID]>    Open bookmark(s) in the browser by ID
```

And the output of `bukubrow --version` is `bukubrow 5.2.0`

So, I had a couple of questions for you:
- Where is the `--install-edge` option? :slightly_smiling_face: 
- When I see an error in the extension, how can I debug it? (sorry, I think this is a question more related to Chrome Extensions rather than `bukubrow`, but I'd appreciate if you help :pray: )

**Comment by samhh** [comment]
Hey there!

Looking at master it looks like this hasn't made it into a release yet. I'll see about preparing a 5.3.0 release shortly.

It's a bit confusing that the README on master doesn't match the latest release, we could consider adopting a master/develop approach as I do with fp-ts-std.

As for debugging, for this WebExtension at least there are two places to debug. The first is the popup itself, where the dev tools can be accessed by right-clicking the icon and hitting "inspect pop-up". The second is the background script which if memory serves handles communication with the host. For that one you'll want to go to [chrome://extensions](chrome://extensions/) and hit "[Inspect views] background page" on the relevant extension.

The ["unknown error" vagueness](https://github.com/samhh/bukubrow-webext/issues/163) is something I hope to improve upon, though that's probably dependent upon me rediscovering the energy to work on the PureScript port of the extension (`purescript` branch in the other repo).

**Comment by samhh** [comment]
5.3.0 released: https://github.com/samhh/bukubrow-host/releases/tag/v5.3.0

Both AUR packages are also updated.

**Comment by farzadmf** [comment]
Thank you very much @samhh for the very useful tips on how to debug stuff

And I used the new version to re-install on Edge and now it's working fine :rocket:
