### ISSUE TITLE
Unable to add new bookmarks in Firefox

### ISSUE THREAD

**Issue by sebelk** [samhh/bukubrow-host#44]
Hi,
I've updated to version bukubrow 5.4.0 and now I cannot add new bookmarks entries. 

This issue happens in Firefox but not in Chrome. I'm reporting here because I've no installed a new version of bukubrow-host.

However I can edit  and delete entries.

Firefox version is 94.0 (64-bit) and bukubrow-webext is 5.0.3.0.

If you need  more information I could provide it.

Thanks in advance!
SB

**Comment by samhh** [comment]
Does the problem still occur if you downgrade the host to 5.3.0?

**Comment by sebelk** [comment]
Yes it does.
I've downgraded to version 5.3.0 and the problem still occur.
![imagen](https://user-images.githubusercontent.com/4109256/144833581-b6148c43-a965-4626-99d5-2a3dcac832ae.png)

Thanks

**Comment by samhh** [comment]
Looks like a CSS/webext issue from the screenshot. Does it still happen if you either downgrade Firefox or try another browser?

**Comment by sebelk** [comment]
I confirm that it was about a Firefox  94.0 issue, I've updated to FF v95.0 and came back to v5.4.0. It works fine now :)
